services:
  api-rest: 
    container_name: ${PROJECT_NAME}-api-rest
    restart: unless-stopped
    build: 
      context: ./api-rest
      target: production
      args:
        - PORT=3000
    ports:
      - "${API_RES_PORT}:3000"
    env_file:
      - ./api-rest/.env.production
    depends_on:
      - db
  e-commerce:
    container_name: ${PROJECT_NAME}-e-commerce
    restart: unless-stopped
    build: 
      context: ./e-commerce
      target: production
      args:
        - PORT=4000
    ports:
      - "${E_COMMERCE_PORT}:4000"     
    env_file:
      - .env
  db:
    image: mongo
    container_name: ${PROJECT_NAME}-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MONGO_VOLUMES}:/data/db
    env_file:
      - .env