services:
  nexjs:
    container_name: ${PROJECT_NAME}-nextjs
    restart: unless-stopped
    build: 
      context: ./e-commerce
      target: production
      args:
        - PORT=3000
    ports:
      - "${PORT}:3000"     
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mongo
    container_name: ${PROJECT_NAME}-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MONGO_VOLUMES}:/data/db
    env_file:
      - .env